name: ci
on:
  workflow_dispatch:
  pull_request:
    paths-ignore: [ README.md ]
  push:
    branches: master
    paths-ignore: [ README.md ]

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  # Mimics the setup of docs.rs, but fails on warnings
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          override: true
      # We need `no-deps` here because `generic-array` we depend on has some obsolete attributes.
      # Can be removed when we update to `signature=3`
      - name: Build docs
        run: env RUSTDOCFLAGS='--cfg docsrs -D warnings' cargo doc --all-features --no-deps
      - name: Run doctests
        run: cargo test --all-features --doc --workspace

  build-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rust-analyzer
      - name: Cache Cargo registry and git
        id: cache-dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'
      - name: Install mdbook-rustdoc-links
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: cargo install mdbook-rustdoc-links
      - name: Build mdBook
        run: mdbook build book
      - name: Run mdBook doctests
        run: mdbook test book

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy
      - run: cargo clippy --all --all-features --tests --benches -- -D warnings
